<template>
	<div class="content">
		<!-- select -->
		<div class="select">
			<SelectGenre @selectGenre="selecGenre" :genres="genres" />
		</div>

		<div class="container">
			<div class="album-list" v-if="loaded">
				<div class="album" v-for="(album, index) in filteredAlbums" :key="index">
					<Album :details="album" />
				</div>
			</div>
			<img v-else class="loading-logo rotate-vert-center" src="@/assets/logo.png" alt="" />
		</div>
	</div>
</template>

<script>
	import axios from 'axios';
	import Album from '@/components/Album';
	import SelectGenre from '@/components/SelectGenre';

	export default {
		name: 'AlbumList',
		components: {
			Album,
			SelectGenre,
		},
		data() {
			return {
				// my data
				albums: [],
				genres: [],
				loaded: false,
				selected: 'all',
			};
		},
		computed: {
			filteredAlbums() {
				if (this.selected === 'all') {
					return this.albums;
				}
				return this.albums.filter(element => {
					if (this.selected.toLowerCase() !== 'all') {
						return element.genre.toLowerCase() === this.selected.toLowerCase();
					}
					return element;
				});
			},
		},
		created() {
			this.getAlbums();
		},
		methods: {
			// my methods
			getAlbums() {
				axios
					.get('https://flynn.boolean.careers/exercises/api/array/music')
					.then(result => {
						this.albums = result.data.response;
						// timeout per simulare un caricamento più lungo, solo a scopo ludico
						setTimeout(() => {
							this.loaded = true;
						}, 150);
						this.getGenres();
					})
					.catch(error => console.log(error));
			},

			selecGenre(value) {
				this.selected = value;
			},

			getGenres() {
				this.genres = ['all'];
				// console.log(this.albums);
				this.albums.forEach(element => {
					if (!this.genres.includes(element.genre)) {
						this.genres.push(element.genre);
					}
				});
				console.log(this.genres);
			},
		},
	};
</script>

<style scoped lang="scss">
	@import '@/styles/vars.scss';

	.container {
		display: flex;
		justify-content: center;
		align-items: center;
	}

	.select {
		display: flex;
		justify-content: center;
		align-items: center;
		padding: 40px;
	}

	.album-list {
		// padding-top: 50px;
		padding-bottom: 20px;
		display: flex;
		flex-wrap: wrap;
		justify-content: center;
		gap: 30px;
	}

	.album {
		display: flex;
		flex-direction: column;
		align-items: center;
		width: calc(100% / 6 - 25px);
		min-width: 200px;
		max-width: 230px;
		padding: 25px;
		background-color: $light-blue;
	}

	.loading-logo {
		max-width: 40%;
		opacity: 0.3;
		padding-top: 100px;
	}

	.rotate-vert-center {
		animation: rotate-vert-center 0.8s cubic-bezier(0.25, 0.46, 0.45, 0.94) infinite both;
	}

	/* ----------------------------------------------
 * Generated by Animista on 2021-5-6 21:49:39
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

	/**
 * ----------------------------------------
 * animation rotate-vert-center
 * ----------------------------------------
 */
	@-webkit-keyframes rotate-vert-center {
		0% {
			-webkit-transform: rotateY(0);
			transform: rotateY(0);
		}
		100% {
			-webkit-transform: rotateY(360deg);
			transform: rotateY(360deg);
		}
	}
	@keyframes rotate-vert-center {
		0% {
			-webkit-transform: rotateY(0);
			transform: rotateY(0);
		}
		100% {
			-webkit-transform: rotateY(360deg);
			transform: rotateY(360deg);
		}
	}
</style>
